Simplified script to find gradlew

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -5,21 +5,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-    - name: List files
-      run: ls -R
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
     - name: Build with Gradle
       run: |
-        GRADLEW_PATH=./gradlew
+        if [ -f "gradlew" ]; then
+          GRADLEW_PATH="./gradlew"
+        elif [ -f "test_repo/gradlew" ]; then
+          GRADLEW_PATH="./test_repo/gradlew"
+        else
+          echo "gradlew not found!"
+          exit 1
+        fi
         chmod +x $GRADLEW_PATH
         $GRADLEW_PATH assembleDebug --no-daemon
     - name: Upload APK
       uses: actions/upload-artifact@v4
       with:
         name: app-debug
-        path: **/app-debug.apk
-        if-no-files-found: error
+        path: "**/app-debug.apk"
