Force build debug and list build dir

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -10,9 +10,9 @@ jobs:
       with:
         java-version: '17'
         distribution: 'temurin'
-    - name: Grant execute permission for gradlew
+    - name: Grant execute permission
       run: chmod +x gradlew
     - name: Build with Gradle
-      run: ./gradlew :app:assembleDebug --stacktrace --info
-    - name: Find APK
-      run: find . -name "*.apk"
+      run: ./gradlew :app:assembleDebug
+    - name: Show build directory
+      run: ls -R app/build || echo "Build directory not found"
